<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $view_title; ?></title>
    <link rel="shortcut icon" href="<?php echo IMG; ?>favicon_aduv.png" type="image/x-icon">
    <link type="text/css" rel="stylesheet" href="<?php echo CSS; ?>error404.css">
    <script type="text/javascript" src="<?php echo JS; ?>error404.js"></script>
</head>
<!-- Icons purchased via Iconfinder under Basic License -->
<body class="permission_denied">