<?php
echo (isset($this->alert)) ? $this->alert : '';

$this->setPartialsDir('partials' . DS . 'perfil');
$this->partial('modalEditarPerfil', array(
    'usuario' => $view_usuario,
    'telefone' => $view_telefone,
    'pessoa' => $view_pessoa,
    'endereco' => $view_endereco
));
$this->partial('modalAlterarSenha');
?>

<ul class="menu nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link text-secondary active" id="resultadoUsuarioTab" data-toggle="tab"
           href="#resultadoPerfil">Perfil</a>
    </li>
</ul>

<div class="tab-content">
    <div class="tab-pane fade show active" id="resultadoPerfil">
        <br/>

        <div class="card shadow-lg">
            <div class="card-body">
                <label class="botaoEsquerda-1 shadow-sm">
                    <button type="button" data-toggle="modal" class="btn btn-light bg-white tooltipTitle"
                            title="Editar" data-target="#modalEditarPerfil">
                        <i class="fas fa-pencil-alt"></i>
                    </button>
                </label>

                <label class="botaoEsquerda-2 shadow-sm">
                    <button type="button" data-toggle="modal" class="btn btn-light bg-white tooltipTitle"
                            title="Alterar senha" data-target="#modalAlterarSenha">
                        <i class="fas fa-key"></i>
                    </button>
                </label>

                <div class="offset-md-4 col-md-4 offset-lg-4 col-lg-4 text-center">
                    <p>
                        <img class="rounded-circle avatar bg-dark tooltipTitle shadow-lg" src="<?php
                        $title = '';

                        if (is_null($view_usuario->imagem)) {
                            $title = 'Icon designed by Eucalyp from Flaticon';
                            $avatar = '';
                            if (is_null($view_pessoa->genero)) {
                                $genero = array('man-' . mt_rand(0, 34), 'woman-' . mt_rand(0, 12));
                                $avatar = $genero[mt_rand(0, 1)];
                            } else {
                                $avatar = ($view_pessoa->genero == 'M') ? 'man-' . mt_rand(0, 34) : 'woman-' . mt_rand(0, 12);
                            }
                            echo IMG . "avatars/usuarios/$avatar";
                        } else {
                            echo UPLOADS . "usuarios/$view_usuario->id_pessoa/$view_usuario->imagem";
                        }
                        ?>" width="180" height="180" title="<?php echo $title; ?>">
                    </p>

                    <hr/>

                    <h5 class="card-title"><?php echo $view_pessoa->nome; ?></h5>
                </div>

                <div class="row">
                    <div class="col-md-6 offset-lg-2 col-lg-4">
                        <p class="card-text"><h6>E-mail</h6><?php echo $view_usuario->email; ?></p>

                        <p class="card-text"><h6>
                            Função</h6><?php echo ($view_usuario->funcao == 'C') ? 'Coordenador' : 'Oficial de promotoria'; ?>
                        </p>

                        <p class="card-text"><h6>CPF</h6><?php echo $view_pessoa->cpf; ?></p>

                        <p class="card-text"><h6>Data de
                            nascimento</h6><?php echo (empty($view_pessoa->data_nascimento)) ? '' : $view_pessoa->data_nascimento->format('d/m/Y'); ?></p>
                    </div>

                    <div class="col-md-6 col-lg-4">
                        <p class="card-text"><h6>Telefone</h6>
                        <?php echo (empty($view_telefone)) ? '' : "($view_telefone->ddd) $view_telefone->numero"; ?></p>

                        <p class="card-text"><h6>Endereço</h6>
                        <?php
                        if (!empty($view_endereco)) {
                            $cidade = Cidade::find_by_id($view_endereco->id_cidade);

                            $uf = Uf::find_by_id($cidade->id_uf);

                            echo "$view_endereco->logradouro, $view_endereco->numero, $view_endereco->complemento, $view_endereco->bairro
                                  <br/>
                                  $cidade->nome/$uf->uf
                                  <br/>
                                  $view_endereco->cep";
                        }
                        ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br/>