<?php
echo (isset($this->alert)) ? $this->alert : '';

$this->setPartialsDir('partials' . DS . 'diligencias');
$this->partial('menu');
$this->partial('modalEventos');
$this->partial('modalInteressado');
$this->partial('modalNovoInteressado');
$this->partial('modalDadosDiligencia');
$this->partial('modalEditarInteressado');
?>

<div class="tab-content">
    <div class="tab-pane fade show active" id="averiguacaoFazenda">
        <br/>

        <?php
        $tipoDiligencia = TipoDiligencia::find_by_tipo('Averiguação em fazenda');

        $this->partial('subMenu', array(
            'tipoDiligencia' => $tipoDiligencia->id
        ));
        ?>
    </div>

    <div class="tab-pane fade" id="averiguacao">
        <br/>

        <?php
        $tipoDiligencia = TipoDiligencia::find_by_tipo('Averiguação');

        $this->partial('subMenu', array(
            'tipoDiligencia' => $tipoDiligencia->id
        ));
        ?>
    </div>

    <div class="tab-pane fade" id="urgente">
        <br/>

        <?php
        $tipoDiligencia = TipoDiligencia::find_by_tipo('Urgente');

        $this->partial('subMenu', array(
            'tipoDiligencia' => $tipoDiligencia->id
        ));
        ?>
    </div>

    <div class="tab-pane fade" id="notificacaoCidade">
        <br/>

        <?php
        $tipoDiligencia = TipoDiligencia::find_by_tipo('Notificação em outra cidade');

        $this->partial('subMenu', array(
            'tipoDiligencia' => $tipoDiligencia->id
        ));
        ?>
    </div>

    <div class="tab-pane fade" id="notificacao">
        <br/>

        <?php
        $tipoDiligencia = TipoDiligencia::find_by_tipo('Notificação');

        $this->partial('subMenu', array(
            'tipoDiligencia' => $tipoDiligencia->id
        ));
        ?>
    </div>

    <div class="tab-pane fade" id="oficioCidade">
        <br/>

        <?php
        $tipoDiligencia = TipoDiligencia::find_by_tipo('Ofício em outra cidade');

        $this->partial('subMenu', array(
            'tipoDiligencia' => $tipoDiligencia->id
        ));
        ?>
    </div>

    <div class="tab-pane fade" id="oficio">
        <br/>

        <?php
        $tipoDiligencia = TipoDiligencia::find_by_tipo('Ofício');

        $this->partial('subMenu', array(
            'tipoDiligencia' => $tipoDiligencia->id
        ));
        ?>
    </div>

    <div class="tab-pane fade" id="ordemMissao">
        <br/>

        <?php
        $tipoDiligencia = TipoDiligencia::find_by_tipo('Ordem de missão');

        $this->partial('subMenu', array(
            'tipoDiligencia' => $tipoDiligencia->id
        ));
        ?>
    </div>

    <?php
    if ($this->auth->getUserRole() == 'C') {
        ?>
        <div class="tab-pane fade" id="cadastrarDiligencias">
            <br/>

            <div class="card shadow-lg">
                <form action="<?php echo $this->printRelativeURL('cadastrar'); ?>" method="post">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 offset-lg-2 col-lg-4">
                                <div class="form-group">
                                    <label for="promotoria">Promotoria</label>

                                    <select class="custom-select" name="promotoria" id="promotoria">
                                        <option selected>Selecione a promotoria</option>
                                        <?php
                                        $promotorias = Promotoria::all();

                                        foreach ($promotorias as $promotoria) {
                                            echo "<option value=$promotoria->id>$promotoria->nome</option>";
                                        }
                                        ?>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="descricao">Descrição</label>

                                    <textarea required class="form-control" name="descricao" id="descricao"
                                              placeholder="Insira a descrição" rows="1"></textarea>
                                </div>

                                <div class="form-group">
                                    <label for="numeroProtocolo">Número de protocolo</label>

                                    <input required type="text" class="form-control" name="numeroProtocolo"
                                           id="numeroProtocolo"
                                           placeholder="Insira o número de protocolo">
                                </div>
                            </div>

                            <div class="col-md-6 col-lg-4">
                                <div class="form-group">
                                    <label for="interessado">Interessado</label>

                                    <div class="w-100">
                                        <div class="input-group">
                                            <input required type="text"
                                                   class="form-control rounded-left rounded-right-0 border-right-0"
                                                   name="interessado"
                                                   id="interessado"
                                                   placeholder="Insira o interessado">

                                            <div class="input-group-append">
                                                <button id="botaoEditarInteressado" type="button"
                                                        class="btn btn-outline-secondary border border-left-0 tooltipTitle d-none"
                                                        data-toggle="modal"
                                                        data-target="#modalEditarInteressado" title="Editar interessado">
                                                    <span><i class="fas fa-user-edit"></i></span>
                                                </button>

                                                <button id="botaoNovoInteressado" type="button"
                                                        class="btn btn-outline-secondary border border-left-0 tooltipTitle"
                                                        data-toggle="modal"
                                                        data-target="#modalNovoInteressado" title="Novo interessado">
                                                    <span><i class="fas fa-user-plus"></i></span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>

                                    <input type="hidden" name="idInteressado" id="idInteressado">
                                </div>

                                <div class="form-group">
                                    <label for="tipoDiligencia">Tipo de diligência</label>

                                    <select class="custom-select" name="tipoDiligencia" id="tipoDiligencia">
                                        <option selected>Selecione o tipo de diligência</option>
                                        <?php
                                        $tiposDiligencias = TipoDiligencia::all();

                                        foreach ($tiposDiligencias as $tipoDiligencia) {
                                            echo "<option value=$tipoDiligencia->id>$tipoDiligencia->tipo</option>";
                                        }
                                        ?>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="prazoCumprimento">Prazo para cumprimento</label>

                                    <input required type="text" class="form-control prazoCumprimento"
                                           name="prazoCumprimento"
                                           placeholder="Selecione a data máxima para o cumprimento">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 offset-lg-2 col-lg-4">
                                <button type="submit" class="btn btn-outline-dark shadow">
                                    <span><i class="fas fa-save"></i></span>
                                    Cadastrar
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <br/>
        </div>
        <?php
    }
    ?>

    <div class="tab-pane fade" id="enviarDiligencias">
        <br/>

        <form action="<?php echo $this->getRelativeURL('enviar'); ?>" method="post">
            <?php
            $this->partial('modalDestinatario');
            ?>

            <button type="button" data-toggle="modal" data-target="#modalDestinatario"
                    class="btn btn-outline-dark shadow">
                <span><i class="fas fa-share-square"></i></span>
                Enviar
            </button>

            <div class="mt-4 row">
                <?php
                $diligencias = Diligencia::all(array(
                    'conditions' => array('status = ?', 'A')
                ));

                foreach ($diligencias as $diligencia) {
                    $evento = Evento::find_by_id_diligencia($diligencia->id, array(
                        'order' => 'data desc',
                        'limit' => 1
                    ));

                    $eventoRegistro = TipoEvento::find_by_tipo('Registro');
                    $eventoRecebimento = TipoEvento::find_by_tipo('Recebimento');

                    if ($evento->id_tipo_evento == $eventoRegistro->id || $evento->id_tipo_evento == $eventoRecebimento->id) {
                        if ($this->auth->getUserId() == $evento->id_autor) {
                            $mandado = Mandado::find_by_id($diligencia->id_mandado);

                            $tipoDiligencia = TipoDiligencia::find_by_id($diligencia->id_tipo_diligencia);

                            $promotoria = Promotoria::find_by_id($mandado->id_promotoria);

                            $interessado = Pessoa::find_by_id($mandado->id_interessado);
                            ?>
                            <div class="col-md-6 col-lg-4">
                                <div class="card-checkbox">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" name="diligencias[]"
                                               id="diligencia<?php echo $diligencia->id; ?>"
                                               value=<?php echo $diligencia->id; ?>>

                                        <label class="custom-control-label"
                                               for="diligencia<?php echo $diligencia->id; ?>">
                                            <div class="card shadow-lg">
                                                <div class="card-body">
                                                    <div class="text-center tooltipTitle" title="Número de protocolo">
                                                        <h5 class="card-title"><?php echo $mandado->numero_protocolo; ?></h5>
                                                    </div>

                                                    <p class="card-text"><h6>
                                                        Promotoria</h6><?php echo $promotoria->nome; ?></p>

                                                    <p class="card-text"><h6>
                                                        Descrição</h6><?php echo $mandado->descricao; ?></p>

                                                    <p class="card-text"><h6>
                                                        Interessado</h6><?php echo $interessado->nome; ?></p>

                                                    <p class="card-text"><h6>Tipo de
                                                        diligência</h6><?php echo $tipoDiligencia->tipo; ?></p>

                                                    <p class="card-text"><h6>Prazo para cumprimento</h6><?php
                                                    echo $diligencia->prazo_cumprimento->format('d/m/Y');
                                                    ?></p>
                                                </div>
                                            </div>
                                        </label>
                                    </div>
                                </div>

                                <br/>
                            </div>
                            <?php
                        }
                    }
                }
                ?>
            </div>
        </form>
    </div>

    <div class="tab-pane fade" id="receberDiligencias">
        <br/>

        <form action="<?php echo $this->getRelativeURL('receber'); ?>" method="post">
            <button type="submit" class="btn btn-outline-dark shadow">
                <span><i class="fas fa-check-square"></i></span>
                Receber
            </button>

            <div class="mt-4 row">
                <?php
                $remessas = Remessa::find_all_by_id_destinatario_and_status($this->auth->getUserId(), 'A');

                foreach ($remessas as $remessa) {
                    $diligencias = Diligencia::getAllByRemessa($remessa->id);

                    $remetente = Pessoa::find_by_id($remessa->id_remetente);

                    $destinatario = Pessoa::find_by_id($remessa->id_destinatario);
                    ?>
                    <div class="col-md-6 col-lg-4">
                        <div class="card-checkbox">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" name="remessas[]"
                                       id="remessa<?php echo $remessa->id; ?>"
                                       value=<?php echo $remessa->id; ?>>

                                <label class="custom-control-label"
                                       for="remessa<?php echo $remessa->id; ?>">
                                    <div class="card shadow-lg">
                                        <div class="card-body">
                                            <div class="text-center tooltipTitle" title="Número da remessa">
                                                <h5 class="card-title"><?php echo $remessa->id; ?></h5>
                                            </div>

                                            <p class="card-text"><h6>
                                                Data da
                                                remessa</h6><?php echo $remessa->data->format('d/m/Y H:i:s'); ?></p>

                                            <p class="card-text"><h6>
                                                Remetente</h6><?php echo $remetente->nome; ?></p>

                                            <p class="card-text"><h6>
                                                Destinatário</h6><?php echo $destinatario->nome; ?></p>

                                            <p class="card-text"><h6>
                                                Diligências</h6>

                                            <div id="diligencias<?php echo $remessa->id; ?>" class="d-none">
                                                <?php
                                                foreach ($diligencias as $diligencia) {
                                                    $mandado = Mandado::find_by_id($diligencia->id_mandado);

                                                    $tipoDiligencia = TipoDiligencia::find_by_id($diligencia->id_tipo_diligencia);

                                                    $promotoria = Promotoria::find_by_id($mandado->id_promotoria);

                                                    $interessado = Pessoa::find_by_id($mandado->id_interessado);
                                                    ?>

                                                    <p class="card-text">
                                                        <button type="button" data-toggle="modal"
                                                                data-target="#modalDadosDiligencia"
                                                                data-diligencia='<?php echo json_encode(array(
                                                                    'numeroProtocolo' => $mandado->numero_protocolo,
                                                                    'promotoria' => $promotoria->nome,
                                                                    'descricao' => $mandado->descricao,
                                                                    'interessado' => $interessado->nome,
                                                                    'tipoDiligencia' => $tipoDiligencia->tipo,
                                                                    'prazoCumprimento' => $diligencia->prazo_cumprimento->format('d/m/Y')
                                                                )); ?>'
                                                                class="btn btn-light bg-white w-100 shadow-sm text-left">
                                                            <?php
                                                            echo $mandado->numero_protocolo;
                                                            ?>
                                                        </button>
                                                    </p>
                                                    <?php
                                                }
                                                ?>
                                            </div>

                                            <div class="mt-4 text-center">
                                                <button type="button"
                                                        class="btn btn-outline-dark shadow diligenciasExpandir"
                                                        data-id="<?php echo $remessa->id; ?>">
                                                    <span><i class="fas fa-arrow-circle-down"></i></span>
                                                </button>
                                            </div>
                                            </p>
                                        </div>
                                    </div>
                                </label>
                            </div>
                        </div>

                        <br/>
                    </div>
                    <?php
                }
                ?>
            </div>
        </form>
    </div>
</div>
