<div id="modalEditarPerfil" class="modal fade modalSeguro" tabindex="-1">
    <div class="modal-dialog modal-lg shadow-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Editar perfil</h5>
            </div>

            <form enctype="multipart/form-data"
                  action="<?php echo $this->getRelativeURL('perfil', false) . DS . 'editar' . DS . $this->auth->getUserId(); ?>"
                  method="post">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group mt-1">
                                <?php
                                $class = '';
                                $backgroundImage = '';

                                if ($view_usuario->imagem != null) {
                                    $class = 'file-ok';
                                    $backgroundImage = UPLOADS . "usuarios/$view_usuario->id_pessoa/$view_usuario->imagem";
                                }
                                ?>
                                <div class="wrap-custom-file">
                                    <input type="file" name="imagem" id="imagemCadastrar" accept=".jpg, .png, .jpeg">

                                    <label class="<?php echo $class; ?>" for="imagemCadastrar"
                                           style="background-image: url('<?php echo $backgroundImage; ?>')">
                                        <span>Imagem de perfil</span>

                                        <i class="fa fa-plus-circle"></i>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="nome">Nome</label>

                                <input required type="text" class="form-control" name="nome" id="nome"
                                       placeholder="Insira o nome completo"
                                       value="<?php echo $view_pessoa->nome; ?>">
                            </div>

                            <div class="form-group">
                                <label for="email">E-mail</label>

                                <input required type="email" class="form-control" name="email" id="email"
                                       placeholder="Insira o e-mail"
                                       value="<?php echo $view_usuario->email; ?>">
                            </div>

                            <div class="form-group">
                                <label for="cpf">CPF</label>

                                <input required type="text" class="form-control" name="cpf" id="cpf"
                                       placeholder="Insira o número de CPF"
                                       value="<?php echo $view_pessoa->cpf; ?>">
                            </div>

                            <div class="form-group">
                                <label for="dataNascimento">Data de nascimento</label>

                                <input required type="text" class="form-control dataNascimento"
                                       name="dataNascimento"
                                       placeholder="Selecione a data de nascimento"
                                       value="<?php echo (empty($view_pessoa->data_nascimento)) ? '' : $view_pessoa->data_nascimento->format('d/m/Y'); ?>">
                            </div>

                            <div class="form-group">
                                <label>Gênero</label>

                                <br/>

                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="opcaoMasculino" name="genero" class="custom-control-input"
                                           value="M"
                                        <?php echo ($view_pessoa->genero == 'M') ? 'checked' : ''; ?>>

                                    <label class="custom-control-label" for="opcaoMasculino">Masculino</label>
                                </div>

                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="opcaoFeminino" name="genero" class="custom-control-input"
                                           value="F"
                                        <?php echo ($view_pessoa->genero == 'F') ? 'checked' : ''; ?>>

                                    <label class="custom-control-label" for="opcaoFeminino">Feminino</label>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-row">
                                <div class="form-group col-4">
                                    <label for="ddd">DDD</label>

                                    <input required type="text" class="form-control" name="ddd" id="ddd"
                                           placeholder="Insira o DDD"
                                           value="<?php echo (empty($view_telefone)) ? '' : $view_telefone->ddd; ?>">
                                </div>

                                <div class="form-group col">
                                    <label for="numeroTelefone">Número</label>

                                    <input required type="text" class="form-control" name="numeroTelefone"
                                           id="numeroTelefone" placeholder="Insira o número de telefone"
                                           value="<?php echo (empty($view_telefone)) ? '' : $view_telefone->numero; ?>">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="logradouro">Logradouro</label>

                                <input required type="text" class="form-control" name="logradouro"
                                       id="logradouro"
                                       placeholder="Insira o nome da rua"
                                       value="<?php echo (empty($view_endereco)) ? '' : $view_endereco->logradouro; ?>">
                            </div>

                            <div class="form-group">
                                <label for="numeroEndereco">Número</label>

                                <input required type="text" class="form-control" name="numeroEndereco"
                                       id="numeroEndereco"
                                       placeholder="Insira o número da casa"
                                       value="<?php echo (empty($view_endereco)) ? '' : $view_endereco->numero; ?>">
                            </div>

                            <div class="form-group">
                                <label for="complemento">Complemento</label>

                                <input required type="text" class="form-control" name="complemento"
                                       id="complemento"
                                       placeholder="Insira o complemento"
                                       value="<?php echo (empty($view_endereco)) ? '' : $view_endereco->complemento; ?>">
                            </div>

                            <div class="form-group">
                                <label for="cep">CEP</label>

                                <input required type="text" class="form-control" name="cep" id="cep"
                                       placeholder="Insira o CEP"
                                       value="<?php echo (empty($view_endereco)) ? '' : $view_endereco->cep; ?>">
                            </div>

                            <div class="form-group">
                                <label for="bairro">Bairro</label>

                                <input required type="text" class="form-control" name="bairro" id="bairro"
                                       placeholder="Insira o bairro"
                                       value="<?php echo (empty($view_endereco)) ? '' : $view_endereco->bairro; ?>">
                            </div>

                            <div class="form-row">
                                <?php
                                $cidade = null;
                                $uf = null;

                                if (!empty($view_endereco)) {
                                    $cidade = Cidade::find_by_id($view_endereco->id_cidade);

                                    $uf = Uf::find_by_id($cidade->id_uf);
                                }
                                ?>

                                <div class="form-group col">
                                    <label for="uf">Estado</label>

                                    <select class="custom-select" name="uf" id="uf"
                                            data-url="<?php echo $this->getRelativeURL('cidades', false) . DS . 'getCidades'; ?>">
                                        <?php
                                        if (empty($uf)) {
                                            ?>
                                            <option selected>Selecione um estado</option>
                                            <?php
                                        } else {
                                            ?>
                                            <option value="<?php echo $uf->id; ?>"
                                                    selected><?php echo $uf->uf; ?></option>
                                            <?php
                                        }

                                        $ufs = Uf::all(array(
                                            'order' => 'uf'
                                        ));

                                        foreach ($ufs as $uf) {
                                            echo "<option value=$uf->id>$uf->uf</option>";
                                        }
                                        ?>
                                    </select>
                                </div>

                                <div class="form-group col">
                                    <label for="cidade">Cidade</label>

                                    <select class="custom-select" name="cidade" id="cidade">
                                        <?php
                                        if (empty($cidade)) {
                                            ?>
                                            <option selected value="0">Selecione um estado primeiro</option>
                                            <?php
                                        } else {
                                            ?>
                                            <option value="<?php echo $cidade->id; ?>"
                                                    selected><?php echo $cidade->nome; ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="cancelar btn btn-outline-danger disabled tooltipTitle shadow"
                            title="Aguarde 3 segundos">
                        <span><i class="fas fa-times"></i></span>
                        Cancelar
                    </button>

                    <button type="submit" class="btn btn-outline-dark shadow">
                        <span><i class="fas fa-save"></i></span>
                        Salvar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>