<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo $view_title; ?></title>

    <link rel="shortcut icon" href="<?php echo IMG; ?>favicon.png" type="image/x-icon">
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/web-fonts-with-css/css/fontawesome-all.min.css"
          type="text/css">
    <link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">

    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

    <script>
        function onSubmit(token) {
            document.getElementById('loginForm').submit();
        }
    </script>
</head>

<body>
<div class="container">
    <br/>

    <br/>

    <div class="row mb-4 mt-5">
        <div class="offset-md-3 col-md-6 offset-lg-4 col-lg-4 text-center">
            <img class="img-fluid" src="<?php echo IMG; ?>logo.png">
        </div>
    </div>

    <div class="row">
        <div class="offset-md-3 col-md-6 offset-lg-4 col-lg-4">
            <?php
            echo (isset($this->alert)) ? $this->alert : '';
            ?>
        </div>
    </div>

    <div class="row">
        <div class="offset-md-3 col-md-6 offset-lg-4 col-lg-4">
            <div class="card">
                <form id="loginForm" action="<?php echo $this->printRelativeURL('acessar'); ?>" method="post">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="email">Email</label>

                            <input required type="email" class="form-control" name="email" id="email"
                                   placeholder="Insira seu e-mail ">
                        </div>

                        <div class="form-group">
                            <label for="senha">Senha</label>

                            <input required type="password" class="form-control" name="senha" id="senha"
                                   placeholder="Insira sua senha">
                        </div>

                        <button class="g-recaptcha btn btn-outline-dark"
                                data-sitekey="6Ldqc2MUAAAAAO7DtP8Br15Z38YhanEGbT_qmawc" data-callback="onSubmit">
                            <span><i class="fas fa-sign-in-alt"></i></span>
                            Acessar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="offset-md-3 col-md-6 offset-lg-4 col-lg-4 text-center">
            <hr/>

            ADUV <?php echo date("Y"); ?> &copy; - Todos os direitos reservados
        </div>
    </div>
</div>

<script src="<?php echo BOWER; ?>jquery/dist/jquery.slim.min.js"></script>
<script src="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>