<div class="row">
    <div class="offset-lg-4 col-lg-4 offset-md-3 col-md-6">
        <div class="card" style="margin-top: 130px">
            <div class="card-body">
                <form action="<?php echo BASE;?>usuarios/acessar/" method="post">
                    <div class="form-group">
                        <label for="nome_usuario">Nome de usuário</label>
                        <input type="text" class="form-control" id="nome_usuario"
                               placeholder="Digite seu nome de usuário aqui...">
                    </div>
                    <div class="form-group">
                        <label for="senha">Senha</label>
                        <input type="password" class="form-control" id="senha" placeholder="Digite sua senha aqui...">
                    </div>
                    <button type="submit" class="btn btn-outline-dark">Acessar</button>
                </form>
            </div>
        </div>
    </div>
</div>
