<?php
echo (isset($this->alert)) ? $this->alert : '';

$this->setPartialsDir('partials' . DS . 'veiculos');
$this->partial('navTabs');
?>

<div class="tab-content">
    <div class="tab-pane fade show active" id="listarVeiculos" role="tabpanel" aria-labelledby="listarVeiculosTab">
        <br/>

    </div>

    <div class="tab-pane fade" id="cadastrarVeiculos" role="tabpanel" aria-labelledby="cadastrarVeiculosTab">
        <br/>

        <div class="card">
            <form enctype="multipart/form-data" action="<?php echo $this->printRelativeURL('cadastrar'); ?>" method="post">
                <div class="card-body">
                    <div class="offset-md-3 col-md-6 offset-lg-4 col-lg-4">
                        <div class="form-group">
                            <label for="imagem">Imagem do veículo</label>

                            <input type="file" class="form-control" name="imagem" id="imagem">
                        </div>

                        <div class="form-group">
                            <label for="marca">Marca</label>

                            <input required type="text" class="form-control" name="marca" id="marca"
                                   placeholder="Insira a marca do veículo">
                        </div>

                        <div class="form-group">
                            <label for="modelo">Modelo</label>

                            <input required type="text" class="form-control" name="modelo" id="modelo"
                                   placeholder="Insira o modelo do veículo">
                        </div>

                        <div class="form-group">
                            <label for="cor">Cor</label>

                            <input required type="text" class="form-control" name="cor" id="cor"
                                   placeholder="Insira a cor do veículo">
                        </div>

                        <div class="form-group">
                            <label for="renavam">Renavam</label>

                            <input required type="text" class="form-control" name="renavam" id="renavam"
                                   placeholder="07600654912">
                        </div>

                        <div class="form-group">
                            <label for="ano">Ano</label>

                            <input required type="text" class="form-control" name="ano" id="ano"
                                   placeholder="2005">
                        </div>

                        <div class="form-group">
                            <label for="placa">Placa</label>

                            <input required type="text" class="form-control" name="placa" id="placa"
                                   placeholder="CYC-6451">
                        </div>
                    </div>
                </div>

                <div class="card-footer bg-white text-center">
                    <button type="submit" class="btn btn-outline-dark">Cadastrar</button>
                </div>
            </form>
        </div>
        <br/>
    </div>
</div>
