<?php
echo (isset($this->alert)) ? $this->alert : '';

$this->setPartialsDir('partials' . DS . 'veiculos');
$this->partial('menu');
?>

<div id="modalEditarVeiculos" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Editar veículo</h5>
            </div>

            <form enctype="multipart/form-data" method="post">
                <div class="modal-body">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group mt-1">
                                    <div class="wrap-custom-file">
                                        <input type="file" name="imagem" id="imagemEditar" accept=".jpg, .png, .jpeg">

                                        <label for="imagemEditar">
                                            <span>Imagem do veículo</span>

                                            <i class="fa fa-plus-circle"></i>
                                        </label>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="modelo">Modelo</label>

                                    <input required type="text" class="form-control" name="modelo" id="modelo"
                                           value="" placeholder="Insira o modelo">
                                </div>

                                <div class="form-group">
                                    <label for="marca">Marca</label>

                                    <input required type="text" class="form-control" name="marca" id="marca"
                                           value="" placeholder="Insira a marca">
                                </div>
                            </div>

                            <div class="col-md-6 ml-auto">
                                <div class="form-group">
                                    <label for="cor">Cor</label>

                                    <input required type="text" class="form-control" name="cor" id="cor"
                                           value="" placeholder="Insira a cor">
                                </div>

                                <div class="form-group">
                                    <label for="renavam">Renavam</label>

                                    <input required type="text" class="form-control" name="renavam" id="renavam"
                                           value="" placeholder="Insira o renavam">
                                </div>

                                <div class="form-group">
                                    <label for="ano">Ano</label>

                                    <input required type="text" class="form-control" name="ano" id="ano"
                                           value="" placeholder="Insira o ano de fabricação">
                                </div>

                                <div class="form-group">
                                    <label for="placa">Placa</label>

                                    <input required type="text" class="form-control" name="placa" id="placa"
                                           value="" placeholder="Insira a placa de identificação">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="cancelar btn btn-outline-danger disabled tooltipTitle" title="Aguarde 3 segundos">
                        <span><i class="fas fa-times"></i></span>
                        Cancelar
                    </button>

                    <button type="submit" class="btn btn-outline-dark">
                        <span><i class="fas fa-save"></i></span>
                        Salvar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="modalQrCode" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body text-center">
                <img>

                <small class="form-text form-muted">
                </small>
            </div>
        </div>
    </div>
</div>

<div class="tab-content">
    <div class="tab-pane fade show active" id="listarVeiculos">
        <br/>

        <div class="row" id="listaVeiculos">
            <?php
            $veiculos = Veiculo::all();
            foreach ($veiculos as $veiculo) {
                ?>
                <div class="col-md-6 col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            <label class="botaoEditarVeiculos">
                                <button type="button" class="btn btn-light bg-white tooltipTitle" data-toggle="modal"
                                        title="Editar"
                                        data-target="#modalEditarVeiculos"
                                        data-veiculo='<?php echo json_encode(array('action' => $this->getRelativeURL('editar'),
                                            'id' => $veiculo->id,
                                            'imagem' => $veiculo->imagem,
                                            'modelo' => $veiculo->modelo,
                                            'marca' => $veiculo->marca,
                                            'renavam' => $veiculo->renavam,
                                            'placa' => $veiculo->placa,
                                            'ano' => $veiculo->ano,
                                            'cor' => $veiculo->cor
                                        )); ?>'>
                                    <span><i class="fas fa-pencil-alt"></i></span>
                                </button>
                            </label>

                            <label class="botaoQrCode">
                                <button type="button" class="btn btn-light bg-white tooltipTitle"
                                        title="Gerar QR Code"
                                        data-id="<?php echo $veiculo->id; ?>"
                                        data-modelo="<?php echo $veiculo->modelo; ?>"
                                        data-toggle="modal"
                                        data-target="#modalQrCode">
                                    <span><i class="fas fa-qrcode"></i></span>
                                </button>
                            </label>

                            <div class="text-center">
                                <p>
                                    <img class="rounded-circle avatar bg-dark tooltipTitle" src="<?php
                                    $title = '';

                                    if (is_null($veiculo->imagem)) {
                                        $title = 'Icon designed by Freepik from Flaticon';
                                        $avatar = 'car-' . mt_rand(0, 7);
                                        echo IMG . "avatars/veiculos/$avatar";
                                    } else {
                                        echo UPLOADS . "veiculos/$veiculo->id/$veiculo->imagem";
                                    }
                                    ?>" width="110" height="110" title="<?php echo $title; ?>">
                                </p>

                                <hr/>

                                <h5 class="card-title tooltipTitle" title="Modelo"><?php echo $veiculo->modelo; ?></h5>
                            </div>

                            <p class="card-text"><h6>Marca</h6><?php echo $veiculo->marca; ?></p>

                            <p class="card-text"><h6>Placa</h6><?php echo $veiculo->placa; ?></p>

                            <div id="dadosVeiculos<?php echo $veiculo->id; ?>" class="d-none">
                                <p class="card-text"><h6>Renavam</h6><?php echo $veiculo->renavam; ?></p>

                                <p class="card-text"><h6>Ano</h6><?php echo $veiculo->ano; ?></p>

                                <p class="card-text"><h6>Cor</h6><?php echo $veiculo->cor; ?></p>
                            </div>

                            <div class="text-center">
                                <button class="btn btn-outline-dark dadosVeiculosExpandir"
                                        data-id="<?php echo $veiculo->id; ?>">
                                    <span><i class="fas fa-arrow-circle-down"></i></span>
                                </button>
                            </div>
                        </div>

                        <div class="card-footer text-center bg-white">
                            <?php
                            if ($veiculo->is_ativo == 1) {
                                ?>
                                <a class="btn btn-outline-danger"
                                   href="<?php echo $this->getRelativeURL('desativar') . '/' . $veiculo->id; ?>">
                                    <span><i class="fas fa-lock"></i></span>
                                    Desativar
                                </a>
                                <?php
                            } else {
                                ?>
                                <a class="btn btn-outline-success"
                                   href="<?php echo $this->getRelativeURL('ativar') . '/' . $veiculo->id; ?>">
                                    <span><i class="fas fa-lock-open"></i></span>
                                    Ativar
                                </a>
                                <?php
                            }
                            ?>
                        </div>
                    </div>
                    <br/>
                </div>
                <?php
            }
            ?>
        </div>
    </div>

    <div class="tab-pane fade" id="cadastrarVeiculos">
        <br/>

        <div class="card">
            <form enctype="multipart/form-data" action="<?php $this->printRelativeURL('cadastrar'); ?>"
                  method="post">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 offset-lg-2 col-lg-4">
                            <div class="form-group mt-1">
                                <div class="wrap-custom-file">
                                    <input type="file" name="imagem" id="imagemCadastrar" accept=".jpg, .png, .jpeg">

                                    <label for="imagemCadastrar">
                                        <span>Imagem do veículo</span>

                                        <i class="fa fa-plus-circle"></i>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="marca">Marca</label>

                                <input required type="text" class="form-control" name="marca" id="marca"
                                       placeholder="Insira a marca">
                            </div>

                            <div class="form-group">
                                <label for="modelo">Modelo</label>

                                <input required type="text" class="form-control" name="modelo" id="modelo"
                                       placeholder="Insira o modelo">
                            </div>
                        </div>

                        <div class="col-md-6 col-lg-4">
                            <div class="form-group">
                                <label for="cor">Cor</label>

                                <input required type="text" class="form-control" name="cor" id="cor"
                                       placeholder="Insira a cor">
                            </div>

                            <div class="form-group">
                                <label for="renavam">Renavam</label>

                                <input required type="text" class="form-control" name="renavam" id="renavam"
                                       placeholder="Insira o renavam">
                            </div>

                            <div class="form-group">
                                <label for="ano">Ano</label>

                                <input required type="text" class="form-control" name="ano" id="ano"
                                       placeholder="Insira o ano de fabricação">
                            </div>

                            <div class="form-group">
                                <label for="placa">Placa</label>

                                <input required type="text" class="form-control" name="placa" id="placa"
                                       placeholder="Insira a placa de identificação">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 offset-lg-2 col-lg-4">
                            <button type="submit" class="btn btn-outline-dark">
                                <span><i class="fas fa-save"></i></span>
                                Cadastrar
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <br/>
    </div>
</div>
