<?php
echo (isset($this->alert)) ? $this->alert : '';

$this->setPartialsDir('partials' . DS . 'veiculos');
$this->partial('menu');
$this->partial('modalEditarVeiculos');
$this->partial('modalQrCode');
$this->partial('modalRegistrosUtilizacao');
?>

<div class="tab-content">
    <div class="tab-pane fade show active" id="listarVeiculos">
        <br/>

        <div class="dropdown filtro">
            <button type="button" class="btn btn-outline-dark shadow-lg">
                <i class="fas fa-filter"></i>
                Filtrar
            </button>

            <div class="dropdown-menu p-4 shadow-lg">
                <div class="form-group mb-0">
                    <label>Situação</label>

                    <br/>

                    <div class="custom-control custom-radio">
                        <input checked class="custom-control-input situacao" type="radio"
                               name="situacao"
                               id="opcaoAtivo"
                               data-target="#ativos">
                        <label class="custom-control-label success" for="opcaoAtivo">Ativo</label>
                    </div>

                    <div class="custom-control custom-radio">
                        <input class="custom-control-input situacao" type="radio"
                               name="situacao"
                               id="opcaoInativo"
                               data-target="#inativos">
                        <label class="custom-control-label danger" for="opcaoInativo">Inativo</label>
                    </div>
                </div>
            </div>

            <nav class="nav d-none">
                <a data-toggle="tab"></a>
            </nav>
        </div>

        <div class="tab-content">
            <div class="tab-pane fade show active" id="ativos">
                <br/>

                <?php
                $this->partial('listarVeiculos', array(
                    'isAtivo' => 1
                ));
                ?>
            </div>

            <div class="tab-pane fade" id="inativos">
                <br/>

                <?php
                $this->partial('listarVeiculos', array(
                    'isAtivo' => 0
                ));
                ?>
            </div>
        </div>
    </div>

    <div class="tab-pane fade" id="cadastrarVeiculos">
        <br/>

        <div class="card shadow-lg">
            <form enctype="multipart/form-data" action="<?php $this->printRelativeURL('cadastrar'); ?>"
                  method="post">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 offset-lg-2 col-lg-4">
                            <div class="form-group mt-1">
                                <div class="wrap-custom-file">
                                    <input type="file" name="imagem" id="imagemCadastrar" accept=".jpg, .png, .jpeg">

                                    <label for="imagemCadastrar">
                                        <span>Imagem do veículo</span>

                                        <i class="fa fa-plus-circle"></i>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="marca">Marca</label>

                                <input required type="text" class="form-control" name="marca" id="marca"
                                       placeholder="Insira a marca">
                            </div>

                            <div class="form-group">
                                <label for="modelo">Modelo</label>

                                <input required type="text" class="form-control" name="modelo" id="modelo"
                                       placeholder="Insira o modelo">
                            </div>
                        </div>

                        <div class="col-md-6 col-lg-4">
                            <div class="form-group">
                                <label for="cor">Cor</label>

                                <input required type="text" class="form-control" name="cor" id="cor"
                                       placeholder="Insira a cor">
                            </div>

                            <div class="form-group">
                                <label for="renavam">Renavam</label>

                                <input required type="text" class="form-control" name="renavam" id="renavam"
                                       placeholder="Insira o renavam">
                            </div>

                            <div class="form-group">
                                <label for="ano">Ano</label>

                                <input required type="text" class="form-control" name="ano" id="ano"
                                       placeholder="Insira o ano de fabricação">
                            </div>

                            <div class="form-group">
                                <label for="placa">Placa</label>

                                <input required type="text" class="form-control" name="placa" id="placa"
                                       placeholder="Insira a placa de identificação">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 offset-lg-2 col-lg-4">
                            <button type="submit" class="btn btn-outline-dark shadow">
                                <span><i class="fas fa-save"></i></span>
                                Cadastrar
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <br/>
    </div>
</div>
