<div id="modalRegistrarUtilizacao" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm shadow-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Registrar uso do veículo</h5>

                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body p-0">
                <video id="qrScanner" width="100%" height="auto" style="margin-bottom: -.40rem;"></video>
            </div>

            <div class="modal-footer text-center">
                <small class="form-text text-muted">Posicione o QR Code próximo da câmera para que ele possa ser
                    lido.
                </small>
            </div>
        </div>
    </div>
</div>

<div id="modalConfirmaRegistro" class="modal fade modalSeguro" tabindex="-1">
    <div class="modal-dialog modal-sm shadow-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="card-title">Você tem certeza?</h5>
            </div>

            <div class="modal-body text-center">
                <small class="form-text text-muted">
                    Você está prestes a registrar o uso do veículo abaixo.
                </small>

                <p>
                    <img class="rounded-circle avatar bg-dark shadow-lg mt-3" width="70"
                         height="70">
                </p>

                <h5 id="veiculo" title="Modelo"></h5>

                <div class="ocorrencia d-none text-left">
                    <hr/>

                    <div class="form-group">
                        <label for="ocorrencia">Ocorrência</label>

                        <textarea class="form-control" name="ocorrencia" id="ocorrencia" placeholder="Insira a ocorrência"
                                  rows="3"></textarea>

                        <small class="form-text text-muted">
                            Favor, informar sobre qualquer ocorrido. Deixar em branco se não houver nada para relatar.
                        </small>
                    </div>
                </div>
            </div>

            <div class="modal-footer bg-white d-block">
                <div class="text-center d-none">
                    <span class="text-success">Registro efetuado com sucesso!</span>

                    <button type="button" class="btn btn-outline-success shadow" data-dismiss="modal">
                        <span><i class="fas fa-times"></i></span>
                        Fechar
                    </button>
                </div>

                <div class="d-flex justify-content-end">
                    <div>
                        <button type="button" class="cancelar btn btn-outline-danger disabled tooltipTitle shadow"
                                title="Aguarde 3 segundos">
                            <span><i class="fas fa-thumbs-down"></i></span>
                            Não
                        </button>

                        <button type="button" id="confirmaRegistro" class="btn btn-outline-success shadow">
                            <span><i class="fas fa-thumbs-up"></i></span>
                            Sim
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>