<div id="modalEditarVeiculos" class="modal fade modalSeguro" tabindex="-1">
    <div class="modal-dialog modal-lg shadow-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Editar veículo</h5>
            </div>

            <form enctype="multipart/form-data" method="post">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group mt-1">
                                <div class="wrap-custom-file">
                                    <input type="file" name="imagem" id="imagemEditar" accept=".jpg, .png, .jpeg">

                                    <label for="imagemEditar">
                                        <span>Imagem do veículo</span>

                                        <i class="fa fa-plus-circle"></i>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="modelo">Modelo</label>

                                <input required type="text" class="form-control" name="modelo" id="modelo"
                                       value="" placeholder="Insira o modelo">
                            </div>

                            <div class="form-group">
                                <label for="marca">Marca</label>

                                <input required type="text" class="form-control" name="marca" id="marca"
                                       value="" placeholder="Insira a marca">
                            </div>
                        </div>

                        <div class="col-md-6 ml-auto">
                            <div class="form-group">
                                <label for="cor">Cor</label>

                                <input required type="text" class="form-control" name="cor" id="cor"
                                       value="" placeholder="Insira a cor">
                            </div>

                            <div class="form-group">
                                <label for="renavam">Renavam</label>

                                <input required type="text" class="form-control" name="renavam" id="renavam"
                                       value="" placeholder="Insira o renavam">
                            </div>

                            <div class="form-group">
                                <label for="ano">Ano</label>

                                <input required type="text" class="form-control" name="ano" id="ano"
                                       value="" placeholder="Insira o ano de fabricação">
                            </div>

                            <div class="form-group">
                                <label for="placa">Placa</label>

                                <input required type="text" class="form-control" name="placa" id="placa"
                                       value="" placeholder="Insira a placa de identificação">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="cancelar btn btn-outline-danger disabled tooltipTitle shadow"
                            title="Aguarde 3 segundos">
                        <span><i class="fas fa-times"></i></span>
                        Cancelar
                    </button>

                    <button type="submit" class="btn btn-outline-dark shadow">
                        <span><i class="fas fa-save"></i></span>
                        Salvar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>