<div id="modalRegistrosUtilizacao" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-lg shadow-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="card-title">Registros de utilização</h5>

                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>

            <div class="modal-body table-responsive">
                <table id="registros" class="table table-borderless table-sm table-hover" style="width: 100% !important;">
                    <thead>
                    <tr>
                        <th>Data do registro</th>
                        <th>Oficial de promotoria</th>
                        <th>Data da baixa</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>