<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" id="listarVeiculosTab" data-toggle="tab" href="#listarVeiculos" role="tab"
           aria-controls="listar" aria-selected="true">Listar</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" id="cadastrarVeiculosTab" data-toggle="tab" href="#cadastrarVeiculos" role="tab"
           aria-controls="cadastrar" aria-selected="false">Cadastrar</a>
    </li>
</ul>