<?php
$diligencias = null;
$id_tipo_diligencia = null;

if (isset($view_id_tipo_diligencia) && !empty($view_id_tipo_diligencia)) {
    $id_tipo_diligencia = $view_id_tipo_diligencia;
    $diligencias = Diligencia::find_all_by_id_tipo_diligencia($id_tipo_diligencia);
}

if (is_null($diligencias) || empty($diligencias)) {
    ?>
    <div class="alert alert-warning show" role="alert">
        <h5 class="alert-heading text-center">Nenhuma diligência desse tipo foi emitida até o presente momento.</h5>
    </div>
    <?php
} else {
    ?>
    <div class="row mb-2">
        <div class="offset-md-2 col-md-8 offset-lg-2 col-lg-8">
            <input type="text" class="form-control" name="pesquisarDiligencias" id="pesquisarDiligencias"
                   placeholder="">
        </div>
    </div>

    <div class="row">
        <div class="offset-md-2 col-md-8 offset-lg-2 col-lg-8">
            <nav class="nav nav-pills flex-column flex-sm-row">
                <a class="flex-sm-fill text-sm-center emAndamentoTab nav-link text-secondary active"
                   id="emAndamentoTab<?php echo $id_tipo_diligencia; ?>" data-toggle="pill"
                   href="#emAndamento<?php echo $id_tipo_diligencia; ?>" role="tab" aria-selected="true">Em
                    Andamento
                    <span class="badge badge-warning text-white"><?php
                        echo count(Diligencia::find_all_by_id_tipo_diligencia_and_status($id_tipo_diligencia, 'A'));
                        ?></span>
                </a>

                <a class="flex-sm-fill text-sm-center emEsperaTab nav-link text-secondary"
                   id="emEsperaTab<?php echo $id_tipo_diligencia; ?>" data-toggle="pill"
                   href="#emEspera<?php echo $id_tipo_diligencia; ?>"
                   role="tab" aria-selected="false">Em Espera
                    <span class="badge badge-danger"><?php
                        echo count(Diligencia::find_all_by_id_tipo_diligencia_and_status($id_tipo_diligencia, 'E'));
                        ?></span>
                </a>

                <a class="flex-sm-fill text-sm-center cumpridaTab nav-link text-secondary"
                   id="cumpridaTab<?php echo $id_tipo_diligencia; ?>" data-toggle="pill"
                   href="#cumprida<?php echo $id_tipo_diligencia; ?>"
                   role="tab" aria-selected="false" title="">Cumpridas
                    <span class="badge badge-success"><?php
                        echo count(Diligencia::find_all_by_id_tipo_diligencia_and_status($id_tipo_diligencia, 'C'));
                        ?></span>
                </a>
            </nav>
        </div>
    </div>

    <div class="tab-content">
        <div class="tab-pane fade show active" id="emAndamento<?php echo $id_tipo_diligencia; ?>" role="tabpanel"
             aria-labelledby="emAndamentoTab<?php echo $id_tipo_diligencia; ?>">
            <br/>

            <?php
            if (!is_null($id_tipo_diligencia)) {
                $this->partial('listarDiligenciasPorStatus', array(
                    'id_tipo_diligencia' => $id_tipo_diligencia,
                    'status' => 'A'
                ));
            }
            ?>
        </div>

        <div class="tab-pane fade" id="emEspera<?php echo $id_tipo_diligencia; ?>" role="tabpanel"
             aria-labelledby="emEsperaTab<?php echo $id_tipo_diligencia; ?>">
            <br/>

            <?php
            if (!is_null($id_tipo_diligencia)) {
                $this->partial('listarDiligenciasPorStatus', array(
                    'id_tipo_diligencia' => $id_tipo_diligencia,
                    'status' => 'E'
                ));
            }
            ?>
        </div>

        <div class="tab-pane fade" id="cumprida<?php echo $id_tipo_diligencia; ?>" role="tabpanel"
             aria-labelledby="cumpridaTab<?php echo $id_tipo_diligencia; ?>">
            <br/>

            <?php
            if (!is_null($id_tipo_diligencia)) {
                $this->partial('listarDiligenciasPorStatus', array(
                    'id_tipo_diligencia' => $id_tipo_diligencia,
                    'status' => 'C'
                ));
            }
            ?>
        </div>
    </div>
    <?php
}
?>
