<?php
$diligencias = null;

if (isset($view_tipoDiligencia) && !empty($view_tipoDiligencia)) {
    if (isset($view_status) && !empty($view_status)) {
        $diligencias = Diligencia::find_all_by_id_tipo_diligencia_and_status($view_tipoDiligencia, $view_status);
    }
}

if (!empty($diligencias)) {
    foreach ($diligencias as $diligencia) {
        if ($this->auth->getUserRole() == 'O') {
            $eventos = Evento::find_all_by_id_diligencia($diligencia->id);

            $registros = false;
            foreach ($eventos as $evento) {
                if ($evento->id_autor == $this->auth->getUserId()) {
                    $registros = true;
                }

                if ($registros) {
                    break;
                }
            }

            if (!$registros) {
                continue;
            }
        }

        $mandado = Mandado::find_by_id($diligencia->id_mandado);

        $tipoDiligencia = TipoDiligencia::find_by_id($diligencia->id_tipo_diligencia);

        $promotoria = Promotoria::find_by_id($mandado->id_promotoria);

        $interessado = Pessoa::find_by_id($mandado->id_interessado);

        $border = '';

        if ($diligencia->status == 'A') {
            $border = 'warning';
        } else if ($diligencia->status == 'E') {
            $border = 'danger';
        } else {
            $border = 'success';
        }
        ?>
        <div class="card border border-<?php echo $border; ?> shadow-lg">
            <div class="card-body">
                <?php
                $eventos = array();

                foreach (Evento::find_all_by_id_diligencia($diligencia->id) as $evento) {
                    $pessoa = Pessoa::find_by_id($evento->id_autor);

                    $tipoEvento = TipoEvento::find_by_id($evento->id_tipo_evento);

                    $eventos[] = array(
                        $evento->data->format('d/m/Y H:i:s'),
                        $tipoEvento->tipo,
                        $pessoa->nome
                    );
                }
                ?>
                <label class="botaoEsquerda-1 shadow-sm">
                    <button type="button" data-toggle="modal"
                            class="btn btn-light bg-white tooltipTitle"
                            title="Eventos ocorridos"
                            data-target="#modalEventos"
                            data-eventos='<?php echo json_encode($eventos); ?>'>
                        <i class="fas fa-calendar-alt"></i>
                    </button>
                </label>

                <?php
                $eventoEnvio = TipoEvento::find_by_tipo('Envio');

                $evento = Evento::find_by_id_diligencia($diligencia->id, array(
                    'order' => 'data desc'
                ));

                if (($evento->id_tipo_evento == $eventoEnvio->id) && ($evento->id_autor == $this->auth->getUserId())) {
                    $remessa = Remessa::getByDiligenciaAndStatus($diligencia->id, 'A')[0];
                    ?>
                    <label class="botaoEsquerda-2 shadow-sm">
                        <a class="btn btn-light bg-white tooltipTitle"
                           title="Gerar remessa"
                           href="<?php echo $this->getRelativeURL('remessas', false) . DS . 'index' . DS . $remessa->id; ?>"
                           target="_blank">
                            <i class="fas fa-file-pdf"></i>
                        </a>
                    </label>
                    <?php
                }
                ?>

                <div class="text-center tooltipTitle" title="Número de protocolo">
                    <h5 class="card-title"><?php echo $mandado->numero_protocolo; ?></h5>
                </div>

                <div class="row">
                    <div class="col-md-6 offset-lg-2 col-lg-4">
                        <p class="card-text"><h6>Promotoria</h6><?php echo $promotoria->nome; ?></p>

                        <p class="card-text"><h6>Descrição</h6><?php echo $mandado->descricao; ?></p>

                        <p class="card-text"><h6>Interessado</h6>
                        <button type="button" class="btn btn-light bg-white shadow-sm w-100 text-left"
                                data-toggle="modal"
                                data-target="#modalInteressado"
                                data-id="<?php echo $interessado->id; ?>">
                            <?php echo $interessado->nome; ?>
                        </button>
                        </p>
                    </div>

                    <div class="col-md-6 col-lg-4">
                        <p class="card-text"><h6>Tipo de diligência</h6><?php echo $tipoDiligencia->tipo; ?></p>

                        <p class="card-text"><h6>Prazo para cumprimento</h6><?php
                        echo $diligencia->prazo_cumprimento->format('d/m/Y');
                        ?></p>
                    </div>
                </div>
            </div>

            <div class="card-footer bg-white">
                <div class="row">
                    <div class="col-sm-4">
                        <?php
                        $evento = Evento::find_by_id_diligencia($diligencia->id, array(
                            'order' => 'data desc'
                        ));

                        $pessoaPosse = Pessoa::find_by_id($evento->id_autor);
                        $usuarioPosse = Usuario::find_by_id_pessoa($pessoaPosse->id);
                        ?>
                        <p class="card-text">
                        <h6>Posse</h6>

                        <img class="rounded-circle avatar bg-dark tooltipTitle" src="<?php
                        $title = '';

                        if (is_null($usuarioPosse->imagem)) {
                            $title = 'Icon designed by Eucalyp from Flaticon';
                            $avatar = '';
                            if (is_null($pessoaPosse->genero)) {
                                $genero = array('man-' . mt_rand(0, 34), 'woman-' . mt_rand(0, 12));
                                $avatar = $genero[mt_rand(0, 1)];
                            } else {
                                $avatar = ($pessoaPosse->genero == 'M') ? 'man-' . mt_rand(0, 34) : 'woman-' . mt_rand(0, 12);
                            }
                            echo IMG . "avatars/usuarios/$avatar";
                        } else {
                            echo UPLOADS . "usuarios/$usuarioPosse->id_pessoa/$usuarioPosse->imagem";
                        }
                        ?>" height="25" width="25" title="<?php echo $title; ?>">

                        <?php echo $pessoaPosse->nome; ?>
                        </p>
                    </div>

                    <div class="col-sm-4 text-center mt-sm-2 mt-lg-2 mt-md-2">
                        <?php
                        if ($pessoaPosse->id == $this->auth->getUserId()) {
                            if ($this->auth->getUserRole() == 'C') {
                                ?>
                                <small class="form-text text-muted mt-0">
                                    Marcar como
                                </small>

                                <?php
                                if ($diligencia->status == 'A') {
                                    ?>
                                    <a class="btn btn-outline-danger shadow"
                                       href="<?php echo $this->getRelativeURL('diligencias', false) . DS . 'emEspera' . DS . $diligencia->id; ?>">
                                        Em espera
                                    </a>
                                    <?php
                                } else if ($diligencia->status == 'E') {
                                    ?>
                                    <a class="btn btn-outline-warning shadow"
                                       href="<?php echo $this->getRelativeURL('diligencias', false) . DS . 'emAndamento' . DS . $diligencia->id; ?>">
                                        Em andamento
                                    </a>
                                    <?php
                                }
                            } else if ($this->auth->getUserRole() == 'O' && $diligencia->status == 'A') {
                                ?>
                                <small class="form-text text-muted mt-0">
                                    Marcar como
                                </small>

                                <a class="btn btn-outline-success shadow"
                                   href="<?php echo $this->getRelativeURL('diligencias', false) . DS . 'cumprida' . DS . $diligencia->id; ?>">
                                    Cumprida
                                </a>
                                <?php
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>

        <br/>
        <?php
    }
}
?>