<ul class="nav nav-tabs">
    <li class="nav-item dropdown show">
        <a class="nav-link text-secondary active dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
           aria-expanded="false">Listar</a>

        <div class="dropdown-menu show">
            <a class="dropdown-item active" id="averiguacaoFazendaTab" data-toggle="tab" href="#averiguacaoFazenda"
               role="tab" aria-selected="true">Averiguação em fazenda</a>

            <a class="dropdown-item" id="averiguacaoTab" data-toggle="tab" href="#averiguacao"
               role="tab" aria-selected="true">Averiguação</a>

            <a class="dropdown-item" id="urgenteTab" data-toggle="tab" href="#urgente"
               role="tab" aria-selected="true">Urgente</a>

            <a class="dropdown-item" id="notificaoCidadeTab" data-toggle="tab" href="#notificacaoCidade"
               role="tab" aria-selected="true">Notificação em outra cidade</a>

            <a class="dropdown-item" id="notificacaoTab" data-toggle="tab" href="#notificacao"
               role="tab" aria-selected="true">Notificação</a>

            <a class="dropdown-item" id="oficioCidadeTab" data-toggle="tab" href="#oficioCidade"
               role="tab" aria-selected="true">Ofício em outra cidade</a>

            <a class="dropdown-item" id="oficioTab" data-toggle="tab" href="#oficio"
               role="tab" aria-selected="true">Ofício</a>

            <a class="dropdown-item" id="ordemMissaoTab" data-toggle="tab" href="#ordemMissao"
               role="tab" aria-selected="true">Ordem de missão</a>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link text-secondary" id="cadastrarDiligenciasTab" data-toggle="tab" href="#cadastrarDiligencias" role="tab"
           aria-selected="false">Cadastrar</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-secondary" id="enviarDiligenciasTab" data-toggle="tab" href="#enviarDiligencias" role="tab"
           aria-selected="false">Enviar</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-secondary" id="receberDiligenciasTab" data-toggle="tab" href="#receberDiligencias" role="tab"
           aria-selected="false">Receber</a>
    </li>
</ul>