<ul class="menu nav nav-tabs">
    <li class="nav-item dropdown show">
        <a class="nav-link text-secondary active dropdown-toggle" data-toggle="dropdown" href="#">Listar</a>

        <div class="dropdown-menu show shadow-lg">
            <a class="dropdown-item active" id="averiguacaoFazendaTab" data-toggle="tab"
               href="#averiguacaoFazenda">Averiguação em fazenda</a>

            <a class="dropdown-item" id="averiguacaoTab" data-toggle="tab"
               href="#averiguacao">Averiguação</a>

            <a class="dropdown-item" id="urgenteTab" data-toggle="tab"
               href="#urgente">Urgente</a>

            <a class="dropdown-item" id="notificaoCidadeTab" data-toggle="tab"
               href="#notificacaoCidade">Notificação em outra cidade</a>

            <a class="dropdown-item" id="notificacaoTab" data-toggle="tab"
               href="#notificacao">Notificação</a>

            <a class="dropdown-item" id="oficioCidadeTab" data-toggle="tab"
               href="#oficioCidade">Ofício em outra cidade</a>

            <a class="dropdown-item" id="oficioTab" data-toggle="tab"
               href="#oficio">Ofício</a>

            <a class="dropdown-item" id="ordemMissaoTab" data-toggle="tab"
               href="#ordemMissao">Ordem de missão</a>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link text-secondary" id="cadastrarDiligenciasTab" data-toggle="tab"
           href="#cadastrarDiligencias">Cadastrar</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-secondary" id="enviarDiligenciasTab" data-toggle="tab"
           href="#enviarDiligencias">Enviar</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-secondary" id="receberDiligenciasTab" data-toggle="tab"
           href="#receberDiligencias">Receber</a>
    </li>
</ul>