<div id="modalDadosDiligencia" class="modal fade" tabindex="-1">
    <div class="modal-dialog shadow-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title tooltipTitle" title="Número de protocolo"></h5>

                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <p class="card-text" id="promotoria"></p>

                        <p class="card-text" id="descricao"></p>

                        <p class="card-text mb-3" id="interessado"></p>
                    </div>

                    <div class="col-md-6">
                        <p class="card-text" id="tipoDiligencia"></p>

                        <p class="card-text" id="prazoCumprimento"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>