<div id="modalEditarInteressado" class="modal fade modalSeguro" tabindex="-1">
    <div class="modal-dialog modal-lg shadow-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Editar interessado</h5>
            </div>

            <div class="modal-body">
                <div class="d-none alert alert-danger fade show">
                    <h5 class="alert-heading text-center">Não foi possível completar as alterações!</h5>

                    <hr/>

                    <div id="alertBody" class="text-center"></div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="nome">Nome</label>

                            <input required type="text" class="form-control" name="nome" id="nome"
                                   placeholder="Insira o nome completo">
                        </div>

                        <div class="form-group">
                            <label for="cpf">CPF</label>

                            <input required type="text" class="form-control" name="cpf" id="cpf"
                                   placeholder="Insira o número de CPF">
                        </div>

                        <div class="form-group">
                            <label for="dataNascimento">Data de nascimento</label>

                            <input required type="text" class="form-control dataNascimento" name="dataNascimento"
                                   placeholder="Selecione a data de nascimento">
                        </div>

                        <div class="form-row">
                            <div class="form-group col-4">
                                <label for="ddd">DDD</label>

                                <input required type="text" class="form-control" name="ddd" id="ddd"
                                       placeholder="Insira o DDD">
                            </div>

                            <div class="form-group col">
                                <label for="numeroTelefone">Número</label>

                                <input required type="text" class="form-control" name="numeroTelefone"
                                       id="numeroTelefone" placeholder="Insira o número de telefone">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cep">CEP</label>

                            <input required type="text" class="form-control" name="cep" id="cep"
                                   placeholder="Insira o CEP">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="logradouro">Logradouro</label>

                            <input required type="text" class="form-control" name="logradouro" id="logradouro"
                                   placeholder="Insira o nome da rua">
                        </div>

                        <div class="form-group">
                            <label for="numeroEndereco">Número</label>

                            <input required type="text" class="form-control" name="numeroEndereco" id="numeroEndereco"
                                   placeholder="Insira o número da casa">
                        </div>

                        <div class="form-group">
                            <label for="complemento">Complemento</label>

                            <input required type="text" class="form-control" name="complemento" id="complemento"
                                   placeholder="Insira o complemento">
                        </div>

                        <div class="form-group">
                            <label for="bairro">Bairro</label>

                            <input required type="text" class="form-control" name="bairro" id="bairro"
                                   placeholder="Insira o bairro">
                        </div>

                        <div class="form-row">
                            <div class="form-group col">
                                <label for="uf">Estado</label>

                                <select class="custom-select" name="uf" id="uf"
                                        data-url="<?php echo $this->getRelativeURL('cidades', false) . DS . 'getCidades'; ?>">
                                    <option>Selecione um estado</option>
                                    <?php
                                    $ufs = Uf::all(array(
                                        'order' => 'uf'
                                    ));

                                    foreach ($ufs as $uf) {
                                        echo "<option value=$uf->id>$uf->uf</option>";
                                    }
                                    ?>
                                </select>
                            </div>

                            <div class="form-group col">
                                <label for="cidade">Cidade</label>

                                <select class="custom-select" name="cidade" id="cidade">
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="cancelar btn btn-outline-danger disabled tooltipTitle shadow"
                        title="Aguarde 3 segundos">
                    <span><i class="fas fa-times"></i></span>
                    Cancelar
                </button>

                <button type="button" id="botaoCadastrar" class="btn btn-outline-dark shadow">
                    <span><i class="fas fa-save"></i></span>
                    Cadastrar
                </button>
            </div>
        </div>
    </div>
</div>