<div id="modalInteressado" class="modal fade" tabindex="-1">
    <div class="modal-dialog shadow-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title tooltipTitle" title="Nome"></h5>

                <button type="button" class="close" data-dismiss="modal">
                    &times;
                </button>
            </div>

            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <p class="card-text" id="cpf"></p>

                        <p class="card-text" id="dataNascimento"></p>

                        <p class="card-text" id="telefone"></p>
                    </div>

                    <div class="col-md-6">
                        <p class="card-text" id="endereco"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>