<?php
$diligencias = null;
$tipoDiligencia = null;

if (isset($view_tipoDiligencia) && !empty($view_tipoDiligencia)) {
    $tipoDiligencia = $view_tipoDiligencia;

    if ($this->auth->getUserRole() == 'C') {
        $diligencias = Diligencia::find_by_id_tipo_diligencia($tipoDiligencia);
    } else {
        $diligencias = Diligencia::getByTipoDiligenciaAndEventosAutor($tipoDiligencia, $this->auth->getUserId());
    }
}

if (empty($diligencias)) {
    ?>
    <div class="alert alert-warning show shadow-lg">
        <h5 class="alert-heading text-center">Nenhuma diligência desse tipo foi emitida até o momento.</h5>
    </div>
    <?php
} else {
    ?>

    <div class="dropdown filtro">
        <button type="button" class="btn btn-outline-dark shadow-lg">
            <i class="fas fa-filter"></i>
            Filtrar
        </button>

        <div class="dropdown-menu p-4 shadow-lg">
            <div class="form-group mb-0">
                <label>Situação</label>

                <br/>

                <div class="custom-control custom-radio">
                    <input checked class="custom-control-input situacao" type="radio"
                           name="situacao<?php echo $tipoDiligencia; ?>"
                           id="opcaoEmAndamento<?php echo $tipoDiligencia; ?>"
                           data-target="#emAndamento<?php echo $tipoDiligencia; ?>">
                    <label class="custom-control-label warning" for="opcaoEmAndamento<?php echo $tipoDiligencia; ?>">Em
                        Andamento</label>
                </div>

                <div class="custom-control custom-radio">
                    <input class="custom-control-input situacao" type="radio"
                           name="situacao<?php echo $tipoDiligencia; ?>"
                           id="opcaoEmEspera<?php echo $tipoDiligencia; ?>"
                           data-target="#emEspera<?php echo $tipoDiligencia; ?>">
                    <label class="custom-control-label danger" for="opcaoEmEspera<?php echo $tipoDiligencia; ?>">Em
                        espera</label>
                </div>

                <div class="custom-control custom-radio">
                    <input class="custom-control-input situacao" type="radio"
                           name="situacao<?php echo $tipoDiligencia; ?>"
                           id="opcaoCumprida<?php echo $tipoDiligencia; ?>"
                           data-target="#cumprida<?php echo $tipoDiligencia; ?>">
                    <label class="custom-control-label success"
                           for="opcaoCumprida<?php echo $tipoDiligencia; ?>">Cumprida</label>
                </div>
            </div>
        </div>

        <nav class="nav d-none">
            <a data-toggle="tab"></a>
        </nav>
    </div>

    <div class="tab-content">
        <div class="tab-pane fade show active" id="emAndamento<?php echo $tipoDiligencia; ?>">
            <br/>

            <?php
            if (!empty($tipoDiligencia)) {
                $this->partial('listarDiligencias', array(
                    'tipoDiligencia' => $tipoDiligencia,
                    'status' => 'A'
                ));
            }
            ?>
        </div>

        <div class="tab-pane fade" id="emEspera<?php echo $tipoDiligencia; ?>">
            <br/>

            <?php
            if (!empty($tipoDiligencia)) {
                $this->partial('listarDiligencias', array(
                    'tipoDiligencia' => $tipoDiligencia,
                    'status' => 'E'
                ));
            }
            ?>
        </div>

        <div class="tab-pane fade" id="cumprida<?php echo $tipoDiligencia; ?>">
            <br/>

            <?php
            if (!empty($tipoDiligencia)) {
                $this->partial('listarDiligencias', array(
                    'tipoDiligencia' => $tipoDiligencia,
                    'status' => 'C'
                ));
            }
            ?>
        </div>
    </div>
    <?php
}
?>
