<nav class="navbar fixed-top navbar-expand navbar-light bg-white border">
    <button type="button" id="sidebarCollapse" class="btn btn-outline-dark">
        <i class="fas fa-align-left"></i>
    </button>

    <ul class="nav nabar-nav">
        <li class="nav-item">
            <a id="link-pesquisar" class="nav-link text-secondary" href="#">
                <i class="fas fa-search"></i>
            </a>
        </li>

        <li class="nav-item">
            <div id="input-pesquisar" class="input-group d-none">
                <input class="form-control" type="search" placeholder="Pesquisar" aria-label="">
            </div>
        </li>
    </ul>

    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link border-right" href="#">
                <i class="fas fa-bell fa-1x"></i>
            </a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarPerfil" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <img src="<?php echo IMG; ?>" class="rounded-circle" height="30" width="30">
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarPerfil">
                <div class="dropdown-divider"></div>

                <a class="dropdown-item" href="<?php $this->printRelativeURL('index', false); ?>/sair/">Sair</a>
            </div>
        </li>
    </ul>
</nav>

<nav id="sidebar" class="navbar navbar-light bg-white border">
    <ul class="nav navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="<?php $this->printRelativeURL('inicio', false); ?>">
                <span><i class="fas fa-home"></i></span>

                <span id="item-text-center">Início</span>
            </a>
        </li>

        <br/>

        <li class="nav-item">
            <a class="nav-link" href="<?php $this->printRelativeURL('diligencias', false); ?>">
                <span><i class="fas fa-tasks"></i></span>

                <span id="item-text-center">Diligências</span>
            </a>
        </li>

        <br/>

        <li class="nav-item">
            <a class="nav-link" href="<?php $this->printRelativeURL('veiculos', false); ?>">
                <span><i class="fas fa-car"></i></span>

                <span id="item-text-center">Veículos</span>
            </a>
        </li>
    </ul>
</nav>