<?php
$this->setPartialsDir('partials' . DS . 'usuarios');
$this->partial('navTabs');
?>

<div class="tab-content">
    <div class="tab-pane active" id="visualizar" role="tabpanel" aria-labelledby="visualizar-tab">
        <br/>

        Visualizar
    </div>

    <div class="tab-pane" id="cadastrar" role="tabpanel" aria-labelledby="cadastrar-tab">
        <br/>

        <div class="card">
            <div class="card-body">
                <div class="offset-md-3 col-md-6 offset-lg-4 col-lg-4">
                    <form action="<?php echo $this->printRelativeURL('cadastrar'); ?>" method="post">
                        <div class="form-group">
                            <label for="nome">Nome</label>

                            <input required type="text" class="form-control" name="nome" id="nome">
                        </div>

                        <div class="form-group">
                            <label for="cpf">CPF</label>

                            <input required type="text" class="form-control" name="cpf" id="cpf"
                                   placeholder="Ex: 927.185.450-03">
                        </div>

                        <div class="form-group">
                            <label for="data_nascimento">Data de nascimento</label>

                            <input required type="text" class="form-control" name="data_nascimento" id="data_nascimento"
                                   placeholder="Ex: 21/09/1998">
                        </div>

                        <div class="form-group">
                            <label for="nome_mae">Nome da mãe</label>

                            <input required type="text" class="form-control" name="nome_mae" id="nome_mae">
                        </div>

                        <div class="form-group">
                            <label for="nome_mae">Nome da mãe</label>

                            <input required type="text" class="form-control" name="nome_mae" id="nome_mae">
                        </div>

                        <button type="submit" class="btn btn-outline-dark">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
