<?php
echo (isset($this->alert)) ? $this->alert : '';

$this->setPartialsDir('partials' . DS . 'usuarios');
$this->partial('menu');
?>

<div class="tab-content">
    <div class="tab-pane fade show active" id="listarUsuarios">
        <br/>

        <div class="dropdown filtro">
            <button type="button" class="btn btn-outline-dark shadow-lg">
                <i class="fas fa-filter"></i>
                Filtrar
            </button>

            <div class="dropdown-menu p-4 shadow-lg">
                <div class="form-group mb-0">
                    <label>Situação</label>

                    <br/>

                    <div class="custom-control custom-radio">
                        <input checked class="custom-control-input situacao" type="radio"
                               name="situacao"
                               id="opcaoAtivo"
                               data-target="#ativos">
                        <label class="custom-control-label success" for="opcaoAtivo">Ativo</label>
                    </div>

                    <div class="custom-control custom-radio">
                        <input class="custom-control-input situacao" type="radio"
                               name="situacao"
                               id="opcaoInativo"
                               data-target="#inativos">
                        <label class="custom-control-label danger" for="opcaoInativo">Inativo</label>
                    </div>
                </div>
            </div>

            <nav class="nav d-none">
                <a data-toggle="tab"></a>
            </nav>
        </div>

        <div class="tab-content">
            <div class="tab-pane fade show active" id="ativos">
                <br/>

                <?php
                $this->partial('listarUsuarios', array(
                    'isAtivo' => 1
                ));
                ?>
            </div>

            <div class="tab-pane fade" id="inativos">
                <br/>

                <?php
                $this->partial('listarUsuarios', array(
                    'isAtivo' => 0
                ));
                ?>
            </div>
        </div>
    </div>

    <div class="tab-pane fade" id="cadastrarUsuarios">
        <br/>

        <div class="card shadow-lg">
            <form action="<?php echo $this->printRelativeURL('cadastrar'); ?>" method="post">
                <div class="card-body">
                    <div class="offset-md-3 col-md-6 offset-lg-4 col-lg-4">
                        <div class="form-group">
                            <label for="nome">Nome</label>

                            <input required type="text" class="form-control" name="nome" id="nome"
                                   placeholder="Insira o nome completo">
                        </div>

                        <div class="form-group">
                            <label for="cpf">CPF</label>

                            <input required type="text" class="form-control" name="cpf" id="cpf"
                                   placeholder="Insira o número de CPF">
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>

                            <input required type="email" class="form-control" name="email" id="email"
                                   placeholder="Insira o e-mail">
                        </div>

                        <div class="form-group">
                            <label>Função</label>

                            <br/>

                            <div class="custom-control custom-radio custom-control-inline">
                                <input class="custom-control-input" type="radio" name="funcao" id="opcaoCoordenador"
                                       value="C">
                                <label class="custom-control-label" for="opcaoCoordenador">Coordenador(a)</label>
                            </div>

                            <div class="custom-control custom-radio custom-control-inline">
                                <input class="custom-control-input" type="radio" name="funcao" id="opcaoOficial"
                                       value="O">
                                <label class="custom-control-label" for="opcaoOficial">Oficial de promotoria</label>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-outline-dark shadow">
                            <span><i class="fas fa-save"></i></span>
                            Cadastrar
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <br/>
    </div>
</div>
