<?php
echo (isset($this->alert)) ? $this->alert : '';

$this->setPartialsDir('partials' . DS . 'usuarios');
$this->partial('navTabs');
?>

<div class="tab-content">
    <div class="tab-pane active" id="visualizar" role="tabpanel" aria-labelledby="visualizar-tab">
        <br/>

        Visualizar
    </div>

    <div class="tab-pane" id="cadastrar" role="tabpanel" aria-labelledby="cadastrar-tab">
        <br/>

        <div class="card">
            <div class="card-body">
                <div class="offset-md-3 col-md-6 offset-lg-4 col-lg-4">
                    <form action="<?php echo $this->printRelativeURL('cadastrar'); ?>" method="post">
                        <div class="form-group">
                            <label for="nome">Nome</label>

                            <input required type="text" class="form-control" name="nome" id="nome"
                                   placeholder="Insira um nome">
                        </div>

                        <div class="form-group">
                            <label for="cpf">CPF</label>

                            <input required type="text" class="form-control" name="cpf" id="cpf"
                                   placeholder="Ex: 927.185.450-03">
                        </div>

                        <div class="form-group">
                            <label for="nome_usuario">Nome de usuário</label>

                            <input required type="text" class="form-control" name="nome_usuario" id="nome_usuario"
                                   placeholder="Insira um nome de usuário">
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>

                            <input required type="email" class="form-control" name="email" id="email"
                                   placeholder="Ex: email@exemplo.com">
                        </div>

                        <div class="form-group">
                            <label>Função</label>

                            <br/>

                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="funcao" id="opcaoCoordenador" value="C">
                                <label class="form-check-label" for="opcaoCoordenador">Coordenador(a)</label>
                            </div>

                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="funcao" id="opcaoOficial" value="O">
                                <label class="form-check-label" for="opcaoOficial">Oficial de promotoria</label>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-outline-dark">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
