<ul class="menu nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link text-secondary active" id="resultadoUsuarioTab" data-toggle="tab"
           href="#resultadoUsuario">Usuário</a>
    </li>
</ul>

<div class="tab-content">
    <div class="tab-pane fade show active" id="resultadoUsuario">
        <br/>

        <?php
        $border = 'border border';
        $border .= ($view_usuario->is_ativo == 1) ? '-success' : '-danger';
        ?>
        <div class="card shadow-lg <?php echo $border; ?>">
            <div class="card-body">
                <div class="offset-md-4 col-md-4 offset-lg-4 col-lg-4 text-center">
                    <p>
                        <img class="rounded-circle avatar bg-dark tooltipTitle shadow-lg" src="<?php
                        $title = '';

                        if (is_null($view_usuario->imagem)) {
                            $title = 'Icon designed by Eucalyp from Flaticon';
                            $avatar = '';
                            if (is_null($view_pessoa->genero)) {
                                $genero = array('man-' . mt_rand(0, 34), 'woman-' . mt_rand(0, 12));
                                $avatar = $genero[mt_rand(0, 1)];
                            } else {
                                $avatar = ($view_pessoa->genero == 'M') ? 'man-' . mt_rand(0, 34) : 'woman-' . mt_rand(0, 12);
                            }
                            echo IMG . "avatars/usuarios/$avatar";
                        } else {
                            echo UPLOADS . "usuarios/$view_usuario->id_pessoa/$view_usuario->imagem";
                        }
                        ?>" width="180" height="180" title="<?php echo $title; ?>">
                    </p>

                    <hr/>

                    <h5 class="card-title"><?php echo $view_pessoa->nome; ?></h5>
                </div>

                <div class="row">
                    <div class="col-md-6 offset-lg-2 col-lg-4">
                        <p class="card-text"><h6>E-mail</h6><?php echo $view_usuario->email; ?></p>

                        <p class="card-text"><h6>
                            Função</h6><?php echo ($view_usuario->funcao == 'C') ? 'Coordenador' : 'Oficial de promotoria'; ?>
                        </p>

                        <p class="card-text"><h6>CPF</h6><?php echo $view_pessoa->cpf; ?></p>

                        <p class="card-text"><h6>Data de
                            nascimento</h6><?php echo (empty($view_pessoa->data_nascimento)) ? '' : $view_pessoa->data_nascimento->format('d/m/Y'); ?></p>
                    </div>

                    <div class="col-md-6 col-lg-4">
                        <p class="card-text"><h6>Telefone</h6>
                        <?php echo (empty($view_telefone)) ? '' : "($view_telefone->ddd) $view_telefone->numero"; ?></p>

                        <p class="card-text"><h6>Endereço</h6>
                        <?php
                        if (!empty($view_endereco)) {
                            $cidade = Cidade::find_by_id($view_endereco->id_cidade);

                            $uf = Uf::find_by_id($cidade->id_uf);

                            echo "$view_endereco->logradouro, $view_endereco->numero, $view_endereco->complemento, $view_endereco->bairro
                                  <br/>
                                  $cidade->nome/$uf->uf
                                  <br/>
                                  $view_endereco->cep";
                        }
                        ?>
                        </p>
                    </div>
                </div>
            </div>

            <div class="card-footer text-center bg-white">
                <?php
                if ($view_usuario->is_ativo == 1) {
                    ?>
                    <a class="btn btn-outline-danger shadow"
                       href="<?php echo $this->getRelativeURL('desativar') . DS . $view_usuario->id_pessoa; ?>">
                        <span><i class="fas fa-lock"></i></span>
                        Desativar
                    </a>
                    <?php
                } else {
                    ?>
                    <a class="btn btn-outline-success shadow"
                       href="<?php echo $this->getRelativeURL('ativar') . DS . $view_usuario->id_pessoa; ?>">
                        <span><i class="fas fa-lock-open"></i></span>
                        Ativar
                    </a>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>

<br/>