<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link text-secondary active" id="resultadoUsuarioTab" data-toggle="tab"
           href="#resultadoUsuario">Resultado</a>
    </li>
</ul>

<div class="tab-content">
    <div class="tab-pane fade show active" id="resultadoUsuario">
        <br/>

        <div class="card">
            <div class="card-body">
                <div class="offset-md-4 col-md-4 offset-lg-4 col-lg-4 text-center">
                    <p>
                        <img class="rounded-circle avatar bg-dark tooltipTitle" src="<?php
                        $title = '';

                        if (is_null($view_usuario->imagem)) {
                            $title = 'Icon designed by Eucalyp from Flaticon';
                            $avatar = '';
                            if (is_null($view_pessoa->genero)) {
                                $genero = array('man-' . mt_rand(0, 34), 'woman-' . mt_rand(0, 12));
                                $avatar = $genero[mt_rand(0, 1)];
                            } else {
                                $avatar = ($view_pessoa->genero == 'M') ? 'man-' . mt_rand(0, 34) : 'woman-' . mt_rand(0, 12);
                            }
                            echo IMG . "avatars/usuarios/$avatar";
                        } else {
                            echo UPLOADS . "usuarios/$view_usuario->id_pessoa/$view_usuario->imagem";
                        }
                        ?>" width="180" height="180" title="<?php echo $title; ?>">
                    </p>

                    <hr/>

                    <h5 class="card-title"><?php echo $view_pessoa->nome; ?></h5>
                </div>

                <div class="row">
                    <div class="col-md-6 offset-lg-2 col-lg-4">
                        <p class="card-text"><h6>E-mail</h6><?php echo $view_usuario->email; ?></p>

                        <p class="card-text"><h6>
                            Função</h6><?php echo ($view_usuario->funcao == 'C') ? 'Coordenador' : 'Oficial de promotoria'; ?>
                        </p>

                        <p class="card-text"><h6>CPF</h6><?php echo $view_pessoa->cpf; ?></p>

                        <p class="card-text"><h6>Data de nascimento</h6><?php echo $view_pessoa->data_nascimento; ?></p>
                    </div>

                    <div class="col-md-6 col-lg-4">
                        <p class="card-text"><h6>Telefones</h6>
                        <?php
                        foreach ($view_telefones as $key => $telefone) {
                            $hr = ($key != count($view_telefones) - 1) ? "<hr/>" : '';
                            echo "<p class='card-text'> ($telefone->ddd) $telefone->numero</p>$hr";
                        }
                        ?>
                        </p>

                        <p class="card-text"><h6>Endereços</h6>
                        <?php
                        foreach ($view_enderecos as $key => $endereco) {
                            $cidade = Cidade::find_by_id($endereco->id_cidade);

                            $uf = Uf::find_by_id($cidade->id_uf);

                            $hr = ($key != count($view_enderecos) - 1) ? "<hr/>" : '';
                            echo "<p class='card-text'> 
                                          $endereco->logradouro, $endereco->numero, $endereco->complemento, $endereco->bairro
                                          <br/>
                                          $cidade->nome/$uf->uf
                                          <br/>
                                          $endereco->cep
                                          </p>
                                          $hr";
                        }
                        ?>
                        </p>
                    </div>
                </div>
            </div>

            <div class="card-footer text-center bg-white">
                <?php
                if ($view_usuario->is_ativo == 1) {
                    ?>
                    <a class="btn btn-outline-danger"
                       href="<?php echo $this->getRelativeURL('desativar') . DS . $view_usuario->id_pessoa; ?>">
                        <span><i class="fas fa-lock"></i></span>
                        Desativar
                    </a>
                    <?php
                } else {
                    ?>
                    <a class="btn btn-outline-success"
                       href="<?php echo $this->getRelativeURL('ativar') . DS . $view_usuario->id_pessoa; ?>">
                        <span><i class="fas fa-lock-open"></i></span>
                        Ativar
                    </a>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>

<br/>