</div>
<div class="container">
    <div class="row">
        <div class="offset-lg-4 col-lg-4 text-center">
            <hr/>
            ADUV <?php echo date("Y"); ?> &copy; - Todos os direitos reservados
        </div>
    </div>
</div>
<script src ="<?php echo BOWER; ?>jquery/dist/jquery.slim.min.js"></script>
<script src ="<?php echo BOWER; ?>popper.js/dist/popper.min.js"></script>
<script src ="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>