<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <hr/>

        ADUV <?php echo date("Y"); ?> &copy; - Todos os direitos reservados
    </div>
</div>
</div>

<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
<script src="<?php echo BOWER; ?>popper.js/dist/umd/popper.min.js"></script>
<script src="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo BOWER; ?>malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="<?php echo JS; ?>main.js"></script>

<?php
echo $add_js;
?>
</body>
</html>