<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo $view_title; ?></title>

    <link rel="shortcut icon" href="<?php echo IMG; ?>favicon.png" type="image/x-icon">
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/web-fonts-with-css/css/fontawesome-all.min.css"
          type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css"
          type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>EasyAutocomplete/dist/easy-autocomplete.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">

    <?php
    echo $add_css;
    ?>
</head>

<body style="padding-top: 83px">
<div class="container-fluid">
    <div id="container">
        <nav class="navbar fixed-top navbar-expand navbar-light bg-white border">
            <button type="button" id="sidebarAppear" class="btn btn-outline-dark">
                <i class="fas fa-bars"></i>
            </button>

            <a class="navbar-brand ml-2" href="#">
                <img id="brand" src="<?php echo IMG . DS . 'logo.png'; ?>" height="40" alt="ADUV">
            </a>

            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item">
                    <button type="button" class="btn btn-outline-dark">
                        <i class="fas fa-bell fa-1x"></i>
                        <span class="badge badge-primary">0</span>
                    </button>
                </li>

                <li class="nav-item dropdown ml-2">
                    <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown">
                        <?php
                        echo Pessoa::getPrimeiroNome($this->auth->getUserId());
                        ?>
                    </button>

                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="dropdown-header text-center">
                            <img class="rounded-circle avatar bg-dark tooltipTitle" src="<?php
                            $title = '';
                            $usuario = Usuario::find_by_id_pessoa($this->auth->getUserId());
                            $pessoa = Pessoa::find_by_id($usuario->id_pessoa);

                            if (is_null($usuario->imagem)) {
                                $title = 'Icon designed by Eucalyp from Flaticon';
                                $avatar = '';
                                if (is_null($pessoa->genero)) {
                                    $genero = array('man-' . mt_rand(0, 34), 'woman-' . mt_rand(0, 12));
                                    $avatar = $genero[mt_rand(0, 1)];
                                } else {
                                    $avatar = ($pessoa->genero == 'M') ? 'man-' . mt_rand(0, 34) : 'woman-' . mt_rand(0, 12);
                                }
                                echo IMG . "avatars/usuarios/$avatar";
                            } else {
                                echo UPLOADS . "usuarios/$usuario->id_pessoa/$usuario->imagem";
                            }
                            ?>" height="70" width="70" title="<?php echo $title; ?>">
                        </div>

                        <div class="dropdown-divider"></div>

                        <a class="dropdown-item text-danger"
                           href="<?php $this->printRelativeURL('index', false); ?>/sair/">
                            <span><i class="fas fa-sign-out-alt"></i></span>
                            <span>Sair</span>
                        </a>
                    </div>
                </li>
            </ul>
        </nav>

        <?php
        echo (isset($this->menu)) ? $this->menu->getMenu() : '';
        ?>

