<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo $view_title; ?></title>

    <link rel="shortcut icon" href="<?php echo IMG; ?>favicon_aduv.png" type="image/x-icon">
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/web-fonts-with-css/css/fontawesome-all.min.css"
          type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css"
          type="text/css">
    <link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
    <link rel="stylesheet" href="<?php echo CSS; ?>sidebar.css" type="text/css">

    <?php
    echo $add_css;
    ?>
</head>

<body style="padding-top: 80px; padding-bottom: 10px;">
<div id="container" class="container-fluid">

    <?php
    (isset($this->menu)) ? require_once $this->menu->getMenu() : '';
    ?>

