<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link text-secondary active" id="listarUsuariosTab" data-toggle="tab" href="#listarUsuarios" role="tab"
           aria-controls="listar" aria-selected="true">Listar</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-secondary" id="cadastrarUsuariosTab" data-toggle="tab" href="#cadastrarUsuarios" role="tab"
           aria-controls="cadastrar" aria-selected="false">Cadastrar</a>
    </li>
</ul>