<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" id="visualizar-tab" data-toggle="tab" href="#visualizar" role="tab"
           aria-controls="visualizar" aria-selected="true">Visualizar</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" id="cadastrar-tab" data-toggle="tab" href="#cadastrar" role="tab"
           aria-controls="cadastrar" aria-selected="false">Cadastrar</a>
    </li>
</ul>