<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" id="listar-tab" data-toggle="tab" href="#listar" role="tab"
           aria-controls="listar" aria-selected="true">Listar</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" id="cadastrar-tab" data-toggle="tab" href="#cadastrar" role="tab"
           aria-controls="cadastrar" aria-selected="false">Cadastrar</a>
    </li>
</ul>